### ISSUE TITLE
The language server crashes when specifying a custom schema

### ISSUE THREAD

**Issue by kmoschcau** [neoclide/coc-yaml#46] opened 2021-08-25 08:05 UTC
I tried this first with a local config, but it happens with the global config as well. As soon as I add this to the config, the server starts crashing and never recovers.
```json
{
  "yaml.schemas": {
    "https://some.company.host/path/to/some/schema.json": ["*file-glob.yaml"]
  }
}
```
I checked in a browser that I can reach the URL and it does respond with a JSON file.

This is the output of `CocCommand workspace.showOutput` and selecting `yaml` when prompted.
```
C:\Users\XXX\.config\coc\extensions\node_modules\coc-yaml\node_modules\yaml-language-server\out\server\src\languageservice\services\yamlSchemaService.js:231
                        schema.schema.url = schemaHandle.url;
                                          ^

TypeError: Cannot create property 'url' on string 'en'
    at C:\Users\XXX\.config\coc\extensions\node_modules\coc-yaml\node_modules\yaml-language-server\out\server\src\languageservice\services\yamlSchemaService.js:231:43
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Here is some version info
```
vim version: NVIM v0.6.0-dev+12-gf515baedc
node version: v16.7.0
coc.nvim version: 0.0.80-3086844413
coc.nvim directory: C:\Users\XXX\AppData\Local\nvim-data\site\pack\packer\start\coc.nvim
term: vtpcon
platform: win32
coc-yaml: 1.4.2
```

**Comment by chemzqm** [comment] 2022-02-20 14:24
Can't reproduce, might be fixed by language server.

**Closed as completed by chemzqm** 2022-02-20 14:24 UTC
